FROM python:3.8-alpine3.15

RUN useradd user

WORKDIR /usr/src/app

COPY ./requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 3308

USER user

CMD [ "python", "./server.py" ]
