version: '3'

services:
    pyserver:
        build: ./
        container_name: server
        ports:
        - "3308:3308"
        image: pyserver
        volumes:
          - .:/usr/src/app
        